# To run local dev with live reload: go install github.com/air-verse/air@latest; air

# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  # Command to build your app
  cmd = "go build -o ./tmp/sqs-ui ./cmd/server"

  # Binary that Air should run after building
  bin = "tmp/sqs-ui"

  # File extensions to watch
  include_ext = ["go"]

  ## We did not include "html", "css", "js", "assets"
  ## because we want this to be reload with a simple f5 or web page reload

  # Directories to ignore (no rebuilds triggered)
  exclude_dir = ["tmp", "bin", "dist", "vendor"]

  # Delay between rebuilds (ms)
  delay = 1000

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
